### ISSUE TITLE
Put tests in a separate class

### ISSUE THREAD

**Issue by skothawala** [spkuehl/Message#6]
Hey,

One thing I'd suggest you do is pull out testing to a different class. The testing should be separate from the actual production code that will be run. Although it's a good idea to always test before running (which is what you are doing in this case), I think there are ways to do that without keeping all your code in one class. Not only will you have a clean "main class" but also you'll be able to scale easier (tests as well as the "main class").

**Comment by spkuehl** [comment]
Thanks, much more readable code now.
